import type { Product, Order, Message } from '../App';

export const mockProducts: Product[] = [
  {
    id: '1',
    sellerId: '2',
    sellerName: 'Nguyễn Thị B',
    title: 'Áo thun Uniqlo trắng cổ tròn - Size M',
    description: 'Áo thun Uniqlo màu trắng, chất liệu cotton 100%, mặc rất mát và thoáng. Đã qua sử dụng nhưng vẫn còn rất mới, không phai màu, không giãn cổ. Giặt sạch sẽ, sẵn sàng để mặc.',
    price: 85000,
    condition: 'like-new',
    category: 'Áo thun',
    size: 'M',
    brand: 'Uniqlo',
    images: [
      'https://images.unsplash.com/photo-1532453288672-3a27e9be9efd?w=800',
      'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=800',
    ],
    location: 'Quận 1, TP.HCM',
    status: 'available',
    views: 234,
    favorites: 45,
    createdAt: new Date('2025-10-25'),
    tags: ['uniqlo', 'cotton', 'basic'],
  },
  {
    id: '2',
    sellerId: '3',
    sellerName: 'Trần Văn C',
    title: 'Quần jean Levi\'s 511 Slim Fit - Size 30',
    description: 'Quần jean Levi\'s 511 chính hãng, màu xanh đậm, form slim fit ôm vừa vặn. Chất denim cao cấp, bền đẹp. Đã mặc vài lần, còn rất mới, không bạc màu hay rách. Phù hợp cho người cao 1m65-1m75.',
    price: 450000,
    condition: 'like-new',
    category: 'Quần jean',
    size: '30',
    brand: 'Levi\'s',
    images: [
      'https://images.unsplash.com/photo-1658910453954-6ca847bb7470?w=800',
      'https://images.unsplash.com/photo-1542272604-787c3835535d?w=800',
    ],
    location: 'Quận 3, TP.HCM',
    status: 'available',
    views: 567,
    favorites: 89,
    createdAt: new Date('2025-10-24'),
    tags: ['levis', 'denim', 'slim-fit'],
  },
  {
    id: '3',
    sellerId: '4',
    sellerName: 'Lê Thị D',
    title: 'Váy hoa vintage phong cách Hàn Quốc',
    description: 'Váy hoa midi vintage siêu xinh, phong cách Hàn Quốc. Chất liệu voan mềm mại, họa tiết hoa nhí dễ thương. Freesize phù hợp từ 45-52kg. Mặc rất thoáng mát mùa hè.',
    price: 150000,
    condition: 'good',
    category: 'Váy',
    size: 'Freesize',
    images: [
      'https://images.unsplash.com/photo-1635447272615-a414b7ea1df4?w=800',
      'https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=800',
    ],
    location: 'Quận 7, TP.HCM',
    status: 'available',
    views: 432,
    favorites: 67,
    createdAt: new Date('2025-10-26'),
    tags: ['vintage', 'korean-style', 'floral'],
  },
  {
    id: '4',
    sellerId: '2',
    sellerName: 'Nguyễn Thị B',
    title: 'Áo sơ mi trắng công sở - Size S',
    description: 'Áo sơ mi trắng form fitted, chất liệu kate mịn, không nhăn. Rất thích hợp đi làm văn phòng. Giặt ủi sạch sẽ, còn rất mới.',
    price: 120000,
    condition: 'like-new',
    category: 'Áo sơ mi',
    size: 'S',
    images: [
      'https://images.unsplash.com/photo-1760287363713-a864ca9b1b1f?w=800',
    ],
    location: 'Quận 1, TP.HCM',
    status: 'available',
    views: 189,
    favorites: 23,
    createdAt: new Date('2025-10-27'),
    tags: ['office', 'formal', 'white'],
  },
  {
    id: '5',
    sellerId: '5',
    sellerName: 'Phạm Văn E',
    title: 'Áo khoác jean Zara - Size L',
    description: 'Áo khoác jean Zara màu xanh nhạt, thiết kế basic dễ phối đồ. Chất jean dày dặn, form oversize trendy. Còn rất đẹp, không bị phai màu.',
    price: 280000,
    condition: 'good',
    category: 'Áo khoác',
    size: 'L',
    brand: 'Zara',
    images: [
      'https://images.unsplash.com/photo-1542318418-572cbf7eb3be?w=800',
      'https://images.unsplash.com/photo-1551028719-00167b16eac5?w=800',
    ],
    location: 'Quận 10, TP.HCM',
    status: 'available',
    views: 678,
    favorites: 124,
    createdAt: new Date('2025-10-23'),
    tags: ['zara', 'denim-jacket', 'oversized'],
  },
  {
    id: '6',
    sellerId: '6',
    sellerName: 'Hoàng Thị F',
    title: 'Đầm dự tiệc màu đỏ sang trọng',
    description: 'Đầm dự tiệc màu đỏ, thiết kế ôm body tôn dáng. Chất liệu lụa cao cấp, có lót trong. Mặc 1 lần đi tiệc nên còn rất mới, như chưa dùng.',
    price: 350000,
    condition: 'new',
    category: 'Đầm',
    size: 'M',
    images: [
      'https://images.unsplash.com/photo-1566174053879-31528523f8ae?w=800',
    ],
    location: 'Quận Bình Thạnh, TP.HCM',
    status: 'available',
    views: 345,
    favorites: 78,
    createdAt: new Date('2025-10-26'),
    tags: ['party', 'formal', 'evening-dress'],
  },
  {
    id: '7',
    sellerId: '3',
    sellerName: 'Trần Văn C',
    title: 'Quần short kaki H&M - Size 32',
    description: 'Quần short kaki màu be, chất liệu cotton thoáng mát. Form straight vừa vặn, có túi hông tiện dụng. Mặc được cả đi chơi lẫn đi làm.',
    price: 95000,
    condition: 'good',
    category: 'Quần short',
    size: '32',
    brand: 'H&M',
    images: [
      'https://images.unsplash.com/photo-1591195853828-11db59a44f6b?w=800',
    ],
    location: 'Quận 3, TP.HCM',
    status: 'available',
    views: 156,
    favorites: 34,
    createdAt: new Date('2025-10-28'),
    tags: ['hm', 'casual', 'summer'],
  },
  {
    id: '8',
    sellerId: '7',
    sellerName: 'Vũ Thị G',
    title: 'Áo len mỏng Mango - Size M',
    description: 'Áo len mỏng Mango màu nâu đất, chất liệu wool pha cotton mềm mại. Form cơ bản, dễ phối đồ. Thích hợp cho thời tiết mát mẻ.',
    price: 180000,
    condition: 'like-new',
    category: 'Áo thun',
    size: 'M',
    brand: 'Mango',
    images: [
      'https://images.unsplash.com/photo-1434389677669-e08b4cac3105?w=800',
    ],
    location: 'Quận 5, TP.HCM',
    status: 'sold',
    views: 289,
    favorites: 56,
    createdAt: new Date('2025-10-22'),
    tags: ['mango', 'sweater', 'autumn'],
  },
];

export const mockOrders: Order[] = [
  {
    id: 'ORD001',
    buyerId: '1',
    sellerId: '2',
    products: [
      {
        product: mockProducts[0],
        quantity: 1,
      },
    ],
    total: 85000,
    status: 'delivered',
    paymentMethod: 'cod',
    shippingAddress: '456 Lê Lợi, Quận 1, TP.HCM',
    createdAt: new Date('2025-10-20'),
  },
  {
    id: 'ORD002',
    buyerId: '1',
    sellerId: '3',
    products: [
      {
        product: mockProducts[1],
        quantity: 1,
      },
    ],
    total: 450000,
    status: 'shipping',
    paymentMethod: 'momo',
    shippingAddress: '456 Lê Lợi, Quận 1, TP.HCM',
    createdAt: new Date('2025-10-25'),
  },
];

export const mockMessages: Message[] = [
  {
    id: 'msg1',
    threadId: 'thread1',
    senderId: '2',
    senderName: 'Nguyễn Thị B',
    content: 'Chào bạn! Sản phẩm còn hàng không ạ?',
    timestamp: new Date('2025-10-27T10:30:00'),
    read: true,
  },
  {
    id: 'msg2',
    threadId: 'thread1',
    senderId: '1',
    senderName: 'Nguyễn Văn A',
    content: 'Dạ còn ạ! Bạn quan tâm sản phẩm nào?',
    timestamp: new Date('2025-10-27T10:32:00'),
    read: true,
  },
  {
    id: 'msg3',
    threadId: 'thread1',
    senderId: '2',
    senderName: 'Nguyễn Thị B',
    content: 'Áo thun Uniqlo ạ. Bạn có thể giảm giá được không?',
    timestamp: new Date('2025-10-27T10:35:00'),
    read: true,
  },
  {
    id: 'msg4',
    threadId: 'thread2',
    senderId: '3',
    senderName: 'Trần Văn C',
    content: 'Sản phẩm này còn bảo hành không bạn?',
    timestamp: new Date('2025-10-28T14:20:00'),
    read: false,
  },
];
